<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <artifactId>awkward-dependencies-examples</artifactId>
    <groupId>com.codesai.katas-java</groupId>
    <version>0.0.1-SNAPSHOT</version>
    <packaging>pom</packaging>

    <name>Awkward Dependencies Examples</name>

    <modules>
        <module>course-duration</module>
        <module>morning-routine</module>
        <module>problematic-discount</module>
        <module>trip-service</module>
    </modules>

</project>
